---

- hosts: 127.0.0.1
  connection: local

  vars:
    - computername: applez
    - git_user_name: Tyler Hoffman
    - git_user_email: tyhoffman1@gmail.com
    - local_home: "{{ lookup('env','HOME') }}"
    - dev_dir: "{{local_home}}/dev"
    - sublime_packages:
        - dest: "GitGutter"
          repo: "https://github.com/jisaacks/GitGutter.git"
          version: "master"
        - dest: "BracketHighlighter"
          repo: "https://github.com/facelessuser/BracketHighlighter.git"
          version: "master"
        - dest: "ApplySyntax"
          repo: "https://github.com/facelessuser/ApplySyntax.git"
          version: "master"
        - dest: "SublimeAllAutocomplete"
          repo: "https://github.com/alienhard/SublimeAllAutocomplete"
          version: "master"

    - projects: # An array of projects to get setup
      - name: tintin
        git: git@github.com:pebble/tintin.git

      - name: libpebble-dev
        git: git@github.com:pebble/libpebble-dev.git

      - name: libpebble2-dev
        git: git@github.com:pebble/libpebble2-dev.git

      - name: pebble-tool-dev
        git: git@github.com:pebble/pebble-tool-dev.git

  tasks:
    - name: homebrew taps
      homebrew_tap: name={{item}} state=present
      with_items: 
        - pebble/pebble-fw
        - caskroom/versions

    - name: homebrew installations
      homebrew: name={{item}} state=present
      with_items:
        - wget
        - fzf
        - rename
        - python
        - tree
        - z
        - zsh
        - fpp
        - curl
        - heroku-toolbelt
        - vim
        - git-extras
        - doxygen
        - freetype
        - llvm
        - libgit2
        - pypy
        - gettext
        - lcov
        - cppcheck
        - curl
        - dpkg
        - trash
        - node
        - ngrok
        - imagemagick
        - arm-none-eabi-gcc
    - name: homebrew cask installations
      homebrew_cask: name={{item}} state=present
      with_items:
        - 1password
        - alfred
        - appcleaner
        - bettertouchtool
        - cyberduck
        - dropbox
        - firefox-beta
        - flux
        - gimp
        - google-chrome
        - plug
        - spotify
        - logitech-control-center
        - evernote
        - iterm2-beta
        - virtualbox
        - virtualbox-extension-pack
        - clion
        - viscosity
        - transmission

    - name: Clone projects from Pebble github
      git: repo={{ item.git }} dest={{ dest_dir }}/{{ item.path }}
      with_items: projects