---

- hosts: 127.0.0.1
  connection: local

  roles:
    # # SHOULD STAY
    # - common
    # - gitconfig

    # # Choose these
    # - sublimetext
    # - clion
    - osx_defaults
    # - firmware

  vars:
    computername: applez

    # Git
    git_user_name: Tyler Hoffman
    git_user_email: tyhoffman1@gmail.com

    # Projects
    project_dir: ~/dev
    projects: # An array of projects to get setup
      - name: tintin
        pip: true
        requirements_file: requirements-osx.txt
      - name: libpebble-dev
        pip: true
      - name: libpebble2-dev
        pip: true
      - name: pebble-tool-dev
        pip: true

    # CLion
    clion_use_native_clipboard: true

    # Sublime
    sublime_packages:
      - dest: "Modific"
        repo: "https://github.com/gornostal/Modific"
        version: "master"
      - dest: "AdvancedNewFile"
        repo: "https://github.com/skuroda/Sublime-AdvancedNewFile"
        version: "master"
      - dest: "Git"
        repo: "https://github.com/kemayo/sublime-text-git"
        version: "master"
      - dest: InsertNums
        repo: "https://github.com/jbrooksuk/InsertNums"
        version: "master"
      - dest: "PrettyJSON"
        repo: "https://github.com/dzhibas/SublimePrettyJson"
        version: "master"
      - dest: "TrailingSpaces"
        repo: "https://github.com/SublimeText/TrailingSpaces"
        version: "master"
      - dest: "TableEditor"
        repo: "https://github.com/vkocubinsky/SublimeTableEditor"
        version: "master"
      - dest: "GenerateUUID"
        repo: "https://github.com/SublimeText/GenerateUUID"
        version: "master"
      - dest: "BracketHighlighter"
        repo: "https://github.com/facelessuser/BracketHighlighter.git"
        version: "master"
      - dest: "SublimeAllAutocomplete"
        repo: "https://github.com/alienhard/SublimeAllAutocomplete"
        version: "master"
      - dest: "Ansible"
        repo: "https://github.com/clifford-github/sublime-ansible"
        version: "master"

  tasks:

    # TODO: Replace with include + with_items when 2.0 ships
    - include: roles/osx_defaults/tasks/dock_app_indicators.yml
    - include: roles/osx_defaults/tasks/dock_apps_spring_loaded.yml
    - include: roles/osx_defaults/tasks/dock_autohide.yml
    - include: roles/osx_defaults/tasks/dock_hidden_apps_transparent.yml
    - include: roles/osx_defaults/tasks/dock_icon_size_small.yml
    - include: roles/osx_defaults/tasks/dock_no_animations.yml
    - include: roles/osx_defaults/tasks/dock_pinning.yml value=middle
    - include: roles/osx_defaults/tasks/dock_position.yml value=bottom
    - include: roles/osx_defaults/tasks/finder_default_view_column.yml
    - include: roles/osx_defaults/tasks/finder_prevent_dsstore_network_drives.yml
    - include: roles/osx_defaults/tasks/finder_remove_spring_loaded_delay.yml
    - include: roles/osx_defaults/tasks/finder_show_all_extensions.yml
    - include: roles/osx_defaults/tasks/finder_show_file_path_title.yml
    - include: roles/osx_defaults/tasks/finder_show_hidden_files.yml
    - include: roles/osx_defaults/tasks/finder_show_status_bar.yml
    - include: roles/osx_defaults/tasks/finder_spotlight_search_current_folder.yml
    - include: roles/osx_defaults/tasks/finder_spring_loaded_folders.yml
    - include: roles/osx_defaults/tasks/input_insane_key_repeat.yml
    - include: roles/osx_defaults/tasks/input_keyboard_all_controls.yml
    - include: roles/osx_defaults/tasks/input_tap_to_click.yml
    - include: roles/osx_defaults/tasks/screenshot_png.yml
    - include: roles/osx_defaults/tasks/screenshots_disable_shadow.yml
    - include: roles/osx_defaults/tasks/uiux_always_expand_print_dialog.yml
    - include: roles/osx_defaults/tasks/uiux_always_expand_save_dialog.yml
    - include: roles/osx_defaults/tasks/uiux_battery_percentage.yml
    - include: roles/osx_defaults/tasks/uiux_disable_app_resume.yml
    - include: roles/osx_defaults/tasks/uiux_disable_smart_typing.yml
    - include: roles/osx_defaults/tasks/uiux_finder_sidebar_icon_size.yml
    - include: roles/osx_defaults/tasks/uiux_quit_print_app_when_finished.yml
    - include: roles/osx_defaults/tasks/uiux_save_locally_default.yml
    - include: roles/osx_defaults/tasks/uiux_scroll_bars_always.yml
    - include: roles/osx_defaults/tasks/uiux_zoom_scroll_ctrl_c.yml

    - name: homebrew installations
      homebrew: name={{item}} state=present
      with_items:
        - curl
        - doxygen
        - dpkg
        - fpp
        - fzf
        - heroku-toolbelt
        - imagemagick
        - ngrok
        - node
        - python
        - rename
        - trash
        - tree
        - vim
        - wget
        - z
        - zsh
    - name: homebrew cask installations
      homebrew_cask: name={{item}} state=present
      with_items:
        - 1password
        - alfred
        - appcleaner
        - bettertouchtool
        - cyberduck
        - evernote
        - firefox-beta
        - flux
        - gimp
        - google-chrome
        - iterm2-beta
        - logitech-control-center
        - plug
        - spotify
        - transmission
        - virtualbox
        - virtualbox-extension-pack

    - name: Create development folder
      file: path={{ project_dir }} state=directory

    - name: Clone Pebble projects
      git: repo=git@github.com:pebble/{{ item.name }}.git dest={{ project_dir }}/{{ item.name }} update=no
      with_items: projects

    # - name: Init pip projects
    #   pip: requirements={{ project_dir }}/{{ item.name }}/{{ item.requirements_file|default("requirements.txt") }}
    #   with_items: projects
    #   when: item.pip
