---

- hosts: 127.0.0.1
  connection: local

  roles:
    - "roderik.superlumic-sublimetext"

  vars:
    - computername: applez
    - git_user_name: Tyler Hoffman
    - git_user_email: tyhoffman1@gmail.com
    - local_home: "{{ lookup('env','HOME') }}"
    - dev_dir: "{{local_home}}/dev"
    - sublime_packages:
        - dest: "GitGutter"
          repo: "https://github.com/jisaacks/GitGutter.git"
          version: "master"
        - dest: "BracketHighlighter"
          repo: "https://github.com/facelessuser/BracketHighlighter.git"
          version: "master"
        - dest: "ApplySyntax"
          repo: "https://github.com/facelessuser/ApplySyntax.git"
          version: "master"
        - dest: "SublimeAllAutocomplete"
          repo: "https://github.com/alienhard/SublimeAllAutocomplete"
          version: "master"

    - pebble_projects: # An array of projects to get setup
      - tintin
      - libpebble-dev
      - libpebble2-dev
      - pebble-tool-dev

  tasks:
    - name: homebrew taps
      homebrew_tap: name={{item}} state=present
      with_items: 
        - pebble/pebble-fw
        - caskroom/versions

    - name: homebrew installations
      homebrew: name={{item}} state=present
      with_items:
        - wget
        - fzf
        - rename
        - python
        - tree
        - z
        - zsh
        - fpp
        - curl
        - heroku-toolbelt
        - vim
        - git-extras
        - doxygen
        - freetype
        - llvm
        - libgit2
        - pypy
        - gettext
        - lcov
        - cppcheck
        - curl
        - dpkg
        - trash
        - node
        - ngrok
        - imagemagick
        - arm-none-eabi-gcc
    - name: homebrew cask installations
      homebrew_cask: name={{item}} state=present
      with_items:
        - 1password
        - alfred
        - appcleaner
        - bettertouchtool
        - cyberduck
        - dropbox
        - firefox-beta
        - flux
        - gimp
        - google-chrome
        - plug
        - spotify
        - logitech-control-center
        - evernote
        - iterm2-beta
        - virtualbox
        - virtualbox-extension-pack
        - clion
        - viscosity
        - transmission

    - name: Create development folder
      file: path={{ dev_dir }} state=directory

    - name: Clone Pebble projects
      git: repo=git@github.com:pebble/{{ item }}.git dest={{ dev_dir }}/{{ item }}
      with_items: pebble_projects