---
# When performing a search, search the current folder by default
- osx_defaults:
    domain: com.apple.finder
    key: 'FXDefaultSearchScope'
    type: string
    value: "SCcf"
  notify: kill finder