---
# Disable smart quotes as they’re annoying when typing code
- osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false

# Disable smart dashes as they’re annoying when typing code
- osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'NSAutomaticDashSubstitutionEnabled'
    type: bool
    value: false